services:
#  idoubtthat-server:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      DB_HOST: mysql
#    depends_on:
#      mysql:
#        condition: service_healthy
#    volumes:
#      - ./build/libs/idoubtthat-server-all.jar:/app/idoubtthat-server.jar

  mysql:
    image: mysql:8
    ports:
      - 9217:3306
    environment:
      MYSQL_DATABASE: "citation"
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_ROOT_PASSWORD: "secret"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
networks:
  default:
