/*
 * This file is generated by jOOQ.
 */
package info.idoubtthat.db.schema.tables


import info.idoubtthat.db.schema.Citation
import info.idoubtthat.db.schema.indexes.REPLIES_REPLY_ID
import info.idoubtthat.db.schema.indexes.REPLIES_REPLY_ID_2
import info.idoubtthat.db.schema.tables.records.RepliesRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Replies(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RepliesRecord>?,
    parentPath: InverseForeignKey<out Record, RepliesRecord>?,
    aliased: Table<RepliesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RepliesRecord>(
    alias,
    Citation.CITATION,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>citation.replies</code>
         */
        val REPLIES: Replies = Replies()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RepliesRecord> = RepliesRecord::class.java

    /**
     * The column <code>citation.replies.reply_id</code>.
     */
    val REPLY_ID: TableField<RepliesRecord, String?> = createField(DSL.name("reply_id"), SQLDataType.VARCHAR(36), this, "")

    /**
     * The column <code>citation.replies.citation_id</code>.
     */
    val CITATION_ID: TableField<RepliesRecord, String?> = createField(DSL.name("citation_id"), SQLDataType.VARCHAR(36), this, "")

    /**
     * The column <code>citation.replies.user_id</code>.
     */
    val USER_ID: TableField<RepliesRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR(36), this, "")

    /**
     * The column <code>citation.replies.reply_commentary</code>.
     */
    val REPLY_COMMENTARY: TableField<RepliesRecord, String?> = createField(DSL.name("reply_commentary"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>citation.replies.valid_from</code>.
     */
    val VALID_FROM: TableField<RepliesRecord, LocalDateTime?> = createField(DSL.name("valid_from"), SQLDataType.LOCALDATETIME(0), this, "")

    /**
     * The column <code>citation.replies.valid_to</code>.
     */
    val VALID_TO: TableField<RepliesRecord, LocalDateTime?> = createField(DSL.name("valid_to"), SQLDataType.LOCALDATETIME(0), this, "")

    private constructor(alias: Name, aliased: Table<RepliesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RepliesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RepliesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>citation.replies</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>citation.replies</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>citation.replies</code> table reference
     */
    constructor(): this(DSL.name("replies"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Citation.CITATION
    override fun getIndexes(): List<Index> = listOf(REPLIES_REPLY_ID, REPLIES_REPLY_ID_2)
    override fun `as`(alias: String): Replies = Replies(DSL.name(alias), this)
    override fun `as`(alias: Name): Replies = Replies(alias, this)
    override fun `as`(alias: Table<*>): Replies = Replies(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Replies = Replies(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Replies = Replies(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Replies = Replies(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Replies = Replies(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Replies = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Replies = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Replies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Replies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Replies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Replies = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Replies = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Replies = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Replies = where(DSL.notExists(select))
}
