/*
 * This file is generated by jOOQ.
 */
package db.schema.tables


import db.schema.Citation
import db.schema.indexes.CITATIONS_CITATION_ID
import db.schema.indexes.CITATIONS_CITATION_ID_2
import db.schema.tables.records.CitationsRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Citations(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CitationsRecord>?,
    parentPath: InverseForeignKey<out Record, CitationsRecord>?,
    aliased: Table<CitationsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CitationsRecord>(
    alias,
    Citation.CITATION,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>citation.citations</code>
         */
        val CITATIONS: Citations = Citations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CitationsRecord> = CitationsRecord::class.java

    /**
     * The column <code>citation.citations.citation_id</code>.
     */
    val CITATION_ID: TableField<CitationsRecord, String?> = createField(DSL.name("citation_id"), SQLDataType.VARCHAR(36), this, "")

    /**
     * The column <code>citation.citations.user_id</code>.
     */
    val USER_ID: TableField<CitationsRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR(36), this, "")

    /**
     * The column <code>citation.citations.url</code>.
     */
    val URL: TableField<CitationsRecord, String?> = createField(DSL.name("url"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>citation.citations.commentary</code>.
     */
    val COMMENTARY: TableField<CitationsRecord, String?> = createField(DSL.name("commentary"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>citation.citations.valid_from</code>.
     */
    val VALID_FROM: TableField<CitationsRecord, LocalDateTime?> = createField(DSL.name("valid_from"), SQLDataType.LOCALDATETIME(0), this, "")

    /**
     * The column <code>citation.citations.valid_to</code>.
     */
    val VALID_TO: TableField<CitationsRecord, LocalDateTime?> = createField(DSL.name("valid_to"), SQLDataType.LOCALDATETIME(0), this, "")

    private constructor(alias: Name, aliased: Table<CitationsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CitationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CitationsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>citation.citations</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>citation.citations</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>citation.citations</code> table reference
     */
    constructor(): this(DSL.name("citations"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Citation.CITATION
    override fun getIndexes(): List<Index> = listOf(CITATIONS_CITATION_ID, CITATIONS_CITATION_ID_2)
    override fun `as`(alias: String): Citations = Citations(DSL.name(alias), this)
    override fun `as`(alias: Name): Citations = Citations(alias, this)
    override fun `as`(alias: Table<*>): Citations = Citations(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Citations = Citations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Citations = Citations(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Citations = Citations(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Citations = Citations(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Citations = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Citations = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Citations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Citations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Citations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Citations = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Citations = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Citations = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Citations = where(DSL.notExists(select))
}
