/*
 * This file is generated by jOOQ.
 */
package info.idoubtthat.db.schema.tables.references


import info.idoubtthat.db.schema.tables.Citations
import info.idoubtthat.db.schema.tables.FlywaySchemaHistory
import info.idoubtthat.db.schema.tables.Replies
import info.idoubtthat.db.schema.tables.Users



/**
 * The table <code>citation.citations</code>.
 */
val CITATIONS: Citations = Citations.CITATIONS

/**
 * The table <code>citation.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>citation.replies</code>.
 */
val REPLIES: Replies = Replies.REPLIES

/**
 * The table <code>citation.users</code>.
 */
val USERS: Users = Users.USERS
