name: Build and Run Docker Compose

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build Kotlin project
        run: ./gradlew assemble

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yaml"

      - name: Run unit tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew integrationTest
