name: Build and Run Docker Compose

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Run build the server
        run: ./gradlew assemble

      - name: Run the pgp tests
        run: ./gradlew pgp:test

      - name: Run the storage tests
        run: ./gradlew storage:test

      - name: Run the server
        run: ./gradlew server:test
